name: build

on:
  push:

jobs:
  my_first_job:
    strategy:
      matrix:
        os: [ ubuntu-latest, ]
        py: [ '3.12' ]

    runs-on:  ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: install project
        run: pip install .[dev]

      - name: do quality check
        run: python -m flake8 minimuh

      - name: test files
        run: python -m pytest

