name: build

on:
  push:

jobs:
  my_job_name:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install project
        run: pip install .

      - name: do quality check
        run: python -m flake minimuh
