name: build

on:
  push:

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install project
        run: pip install .[dev]

      - name: do quality check
        run: python -m flake8 minimuh

  second_job:
    runs-on: ubuntu-latest
    needs: [my_first_job]

    steps:
      - name: congratulate
        run: echo "good job!"
